spring:
    application:
        name: bankingapp-registry-service

server:
    port: 8761

eureka:
    client:
        service-url:
          default-zone: http://localhost:8761
        register-with-eureka: false
        fetch-registry: false