spring:
  application:
    name: bankingapp-fund-transfer-service
    
  kafka:
   bootstrap-servers: kafka:9092

  datasource:
    url: jdbc:postgresql://fund-transfer-db:5432/bankingapp-fundTransfer-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    formatSql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
 port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://bankingapp-registry-service:8761/eureka
      register-with-eureka: true
      fetch-registry: false

management:
 endpoints:
   web:
     exposure:
       include: "*"

bankingapp:
 kafka:
   topic:
     fund-Validation: fund-Validation
     Transaction: transaction

