spring:
  application:
    name: bankingapp-fund-transfer-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingapp-fundTransfer-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true

server:
  port: 8093

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

bankingapp:
  kafka:
    topic:
      fund-Validation: fund-Validation
      Transaction: transaction

